// Auto generated inclusion directives for clangTooling
#include <cstddef>
#include <cstdint>
#include <compare>
#include <clang/Tooling/ASTDiff/ASTDiff.h>
#include <clang/Tooling/ASTDiff/ASTDiffInternal.h>
#include <clang/Tooling/AllTUsExecution.h>
#include <clang/Tooling/ArgumentsAdjusters.h>
#include <clang/Tooling/CommonOptionsParser.h>
#include <clang/Tooling/CompilationDatabase.h>
#include <clang/Tooling/CompilationDatabasePluginRegistry.h>
#include <clang/Tooling/Core/Diagnostic.h>
#include <clang/Tooling/Core/Replacement.h>
#include <clang/Tooling/DependencyScanning/DependencyScanningFilesystem.h>
#include <clang/Tooling/DependencyScanning/DependencyScanningService.h>
#include <clang/Tooling/DependencyScanning/DependencyScanningTool.h>
#include <clang/Tooling/DependencyScanning/DependencyScanningWorker.h>
#include <clang/Tooling/DependencyScanning/ModuleDepCollector.h>
#include <clang/Tooling/DiagnosticsYaml.h>
#include <clang/Tooling/Execution.h>
#include <clang/Tooling/FileMatchTrie.h>
#include <clang/Tooling/FixIt.h>
#include <clang/Tooling/Inclusions/HeaderAnalysis.h>
#include <clang/Tooling/Inclusions/HeaderIncludes.h>
#include <clang/Tooling/Inclusions/IncludeStyle.h>
#include <clang/Tooling/Inclusions/StandardLibrary.h>
#include <clang/Tooling/JSONCompilationDatabase.h>
#include <clang/Tooling/NodeIntrospection.h>
#include <clang/Tooling/Refactoring.h>
#include <clang/Tooling/Refactoring/ASTSelection.h>
#include <clang/Tooling/Refactoring/AtomicChange.h>
#include <clang/Tooling/Refactoring/Extract/Extract.h>
#include <clang/Tooling/Refactoring/Extract/SourceExtraction.h>
#include <clang/Tooling/Refactoring/Lookup.h>
#include <clang/Tooling/Refactoring/RecursiveSymbolVisitor.h>
#include <clang/Tooling/Refactoring/RefactoringAction.h>
#include <clang/Tooling/Refactoring/RefactoringActionRule.h>
#include <clang/Tooling/Refactoring/RefactoringActionRuleRequirements.h>
#include <clang/Tooling/Refactoring/RefactoringActionRules.h>
#include <clang/Tooling/Refactoring/RefactoringActionRulesInternal.h>
#include <clang/Tooling/Refactoring/RefactoringDiagnostic.h>
#include <clang/Tooling/Refactoring/RefactoringOption.h>
#include <clang/Tooling/Refactoring/RefactoringOptionVisitor.h>
#include <clang/Tooling/Refactoring/RefactoringOptions.h>
#include <clang/Tooling/Refactoring/RefactoringResultConsumer.h>
#include <clang/Tooling/Refactoring/RefactoringRuleContext.h>
#include <clang/Tooling/Refactoring/Rename/RenamingAction.h>
#include <clang/Tooling/Refactoring/Rename/SymbolName.h>
#include <clang/Tooling/Refactoring/Rename/SymbolOccurrences.h>
#include <clang/Tooling/Refactoring/Rename/USRFinder.h>
#include <clang/Tooling/Refactoring/Rename/USRFindingAction.h>
#include <clang/Tooling/Refactoring/Rename/USRLocFinder.h>
#include <clang/Tooling/RefactoringCallbacks.h>
#include <clang/Tooling/ReplacementsYaml.h>
#include <clang/Tooling/StandaloneExecution.h>
#include <clang/Tooling/Syntax/BuildTree.h>
#include <clang/Tooling/Syntax/Mutations.h>
#include <clang/Tooling/Syntax/Nodes.h>
#include <clang/Tooling/Syntax/TokenBufferTokenManager.h>
#include <clang/Tooling/Syntax/TokenManager.h>
#include <clang/Tooling/Syntax/Tokens.h>
#include <clang/Tooling/Syntax/Tree.h>
#include <clang/Tooling/ToolExecutorPluginRegistry.h>
#include <clang/Tooling/Tooling.h>
#include <clang/Tooling/Transformer/MatchConsumer.h>
#include <clang/Tooling/Transformer/Parsing.h>
#include <clang/Tooling/Transformer/RangeSelector.h>
#include <clang/Tooling/Transformer/RewriteRule.h>
#include <clang/Tooling/Transformer/SourceCode.h>
#include <clang/Tooling/Transformer/SourceCodeBuilders.h>
#include <clang/Tooling/Transformer/Stencil.h>
#include <clang/Tooling/Transformer/Transformer.h>
