# SPDX-FileCopyrightText: © 2024 Ashley Hawkins <awhawkins@proton.me>
# SPDX-FileContributor: Ashley Hawkins <awhawkins@proton.me>
#
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
    - id: reuse
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.1
  hooks:
  - id: clang-format
    files: 'src/.*\.(c|cc|cpp|h|hh|hpp|cxx|hxx)$'
