// Auto generated inclusion directives for clangLex
#include <cstddef>
#include <cstdint>
#include <compare>
#include <clang/Lex/CodeCompletionHandler.h>
#include <clang/Lex/DependencyDirectivesScanner.h>
#include <clang/Lex/DirectoryLookup.h>
#include <clang/Lex/ExternalPreprocessorSource.h>
#include <clang/Lex/HeaderMap.h>
#include <clang/Lex/HeaderMapTypes.h>
#include <clang/Lex/HeaderSearch.h>
#include <clang/Lex/HeaderSearchOptions.h>
#include <clang/Lex/LexDiagnostic.h>
#include <clang/Lex/Lexer.h>
#include <clang/Lex/LiteralSupport.h>
#include <clang/Lex/MacroArgs.h>
#include <clang/Lex/MacroInfo.h>
#include <clang/Lex/ModuleLoader.h>
#include <clang/Lex/ModuleMap.h>
#include <clang/Lex/MultipleIncludeOpt.h>
#include <clang/Lex/PPCallbacks.h>
#include <clang/Lex/PPConditionalDirectiveRecord.h>
#include <clang/Lex/Pragma.h>
#include <clang/Lex/PreprocessingRecord.h>
#include <clang/Lex/Preprocessor.h>
#include <clang/Lex/PreprocessorLexer.h>
#include <clang/Lex/PreprocessorOptions.h>
#include <clang/Lex/ScratchBuffer.h>
#include <clang/Lex/Token.h>
#include <clang/Lex/TokenConcatenation.h>
#include <clang/Lex/TokenLexer.h>
#include <clang/Lex/VariadicMacroSupport.h>
