// Auto generated inclusion directives for clangBasic
#include <cstddef>
#include <cstdint>
#include <compare>
#include <clang/Basic/ABI.h>
#include <clang/Basic/AddressSpaces.h>
#include <clang/Basic/AlignedAllocation.h>
#include <clang/Basic/AllDiagnostics.h>
#include <clang/Basic/AttrKinds.h>
#include <clang/Basic/AttrSubjectMatchRules.h>
#include <clang/Basic/AttributeCommonInfo.h>
#include <clang/Basic/Attributes.h>
#include <clang/Basic/BitmaskEnum.h>
#include <clang/Basic/Builtins.h>
#include <clang/Basic/CLWarnings.h>
#include <clang/Basic/CapturedStmt.h>
#include <clang/Basic/CharInfo.h>
#include <clang/Basic/CodeGenOptions.h>
#include <clang/Basic/CommentOptions.h>
#include <clang/Basic/Cuda.h>
#include <clang/Basic/CustomizableOptional.h>
#include <clang/Basic/DarwinSDKInfo.h>
#include <clang/Basic/Diagnostic.h>
#include <clang/Basic/DiagnosticAST.h>
#include <clang/Basic/DiagnosticAnalysis.h>
#include <clang/Basic/DiagnosticCategories.h>
#include <clang/Basic/DiagnosticComment.h>
#include <clang/Basic/DiagnosticCrossTU.h>
#include <clang/Basic/DiagnosticDriver.h>
#include <clang/Basic/DiagnosticError.h>
#include <clang/Basic/DiagnosticFrontend.h>
#include <clang/Basic/DiagnosticIDs.h>
#include <clang/Basic/DiagnosticLex.h>
#include <clang/Basic/DiagnosticOptions.h>
#include <clang/Basic/DiagnosticParse.h>
#include <clang/Basic/DiagnosticRefactoring.h>
#include <clang/Basic/DiagnosticSema.h>
#include <clang/Basic/DiagnosticSerialization.h>
#include <clang/Basic/DirectoryEntry.h>
#include <clang/Basic/ExceptionSpecificationType.h>
#include <clang/Basic/ExpressionTraits.h>
#include <clang/Basic/FileEntry.h>
#include <clang/Basic/FileManager.h>
#include <clang/Basic/FileSystemOptions.h>
#include <clang/Basic/FileSystemStatCache.h>
#include <clang/Basic/HLSLRuntime.h>
#include <clang/Basic/HeaderInclude.h>
#include <clang/Basic/IdentifierTable.h>
#include <clang/Basic/JsonSupport.h>
#include <clang/Basic/LLVM.h>
#include <clang/Basic/Lambda.h>
#include <clang/Basic/LangOptions.h>
#include <clang/Basic/LangStandard.h>
#include <clang/Basic/Linkage.h>
#include <clang/Basic/MacroBuilder.h>
#include <clang/Basic/MakeSupport.h>
#include <clang/Basic/Module.h>
#include <clang/Basic/NoSanitizeList.h>
#include <clang/Basic/ObjCRuntime.h>
#include <clang/Basic/OpenCLOptions.h>
#include <clang/Basic/OpenMPKinds.h>
#include <clang/Basic/OperatorKinds.h>
#include <clang/Basic/OperatorPrecedence.h>
#include <clang/Basic/ParsedAttrInfo.h>
#include <clang/Basic/PartialDiagnostic.h>
#include <clang/Basic/PlistSupport.h>
#include <clang/Basic/PragmaKinds.h>
#include <clang/Basic/PrettyStackTrace.h>
#include <clang/Basic/ProfileList.h>
#include <clang/Basic/SanitizerSpecialCaseList.h>
#include <clang/Basic/Sanitizers.h>
#include <clang/Basic/Sarif.h>
#include <clang/Basic/SourceLocation.h>
#include <clang/Basic/SourceManager.h>
#include <clang/Basic/SourceManagerInternals.h>
#include <clang/Basic/Specifiers.h>
#include <clang/Basic/Stack.h>
#include <clang/Basic/SyncScope.h>
#include <clang/Basic/TargetBuiltins.h>
#include <clang/Basic/TargetCXXABI.h>
#include <clang/Basic/TargetID.h>
#include <clang/Basic/TargetInfo.h>
#include <clang/Basic/TargetOptions.h>
#include <clang/Basic/TemplateKinds.h>
#include <clang/Basic/Thunk.h>
#include <clang/Basic/TokenKinds.h>
#include <clang/Basic/TypeTraits.h>
#include <clang/Basic/Version.h>
#include <clang/Basic/Visibility.h>
#include <clang/Basic/XRayInstr.h>
#include <clang/Basic/XRayLists.h>
