// Auto generated inclusion directives for clangSema
#include <cstddef>
#include <cstdint>
#include <compare>
#include <clang/Sema/AnalysisBasedWarnings.h>
#include <clang/Sema/CXXFieldCollector.h>
#include <clang/Sema/CleanupInfo.h>
#include <clang/Sema/CodeCompleteConsumer.h>
#include <clang/Sema/CodeCompleteOptions.h>
#include <clang/Sema/DeclSpec.h>
#include <clang/Sema/DelayedDiagnostic.h>
#include <clang/Sema/Designator.h>
#include <clang/Sema/EnterExpressionEvaluationContext.h>
#include <clang/Sema/ExternalSemaSource.h>
#include <clang/Sema/HLSLExternalSemaSource.h>
#include <clang/Sema/IdentifierResolver.h>
#include <clang/Sema/Initialization.h>
#include <clang/Sema/Lookup.h>
#include <clang/Sema/MultiplexExternalSemaSource.h>
#include <clang/Sema/ObjCMethodList.h>
#include <clang/Sema/Overload.h>
#include <clang/Sema/Ownership.h>
#include <clang/Sema/ParsedAttr.h>
#include <clang/Sema/ParsedTemplate.h>
#include <clang/Sema/RISCVIntrinsicManager.h>
#include <clang/Sema/Scope.h>
#include <clang/Sema/ScopeInfo.h>
#include <clang/Sema/Sema.h>
#include <clang/Sema/SemaConcept.h>
#include <clang/Sema/SemaConsumer.h>
#include <clang/Sema/SemaDiagnostic.h>
#include <clang/Sema/SemaFixItUtils.h>
#include <clang/Sema/SemaInternal.h>
#include <clang/Sema/SemaLambda.h>
#include <clang/Sema/Template.h>
#include <clang/Sema/TemplateDeduction.h>
#include <clang/Sema/TemplateInstCallback.h>
#include <clang/Sema/TypoCorrection.h>
#include <clang/Sema/Weak.h>
