// Auto generated inclusion directives for clangFrontend
#include <cstddef>
#include <cstdint>
#include <compare>
#include <clang/Frontend/ASTConsumers.h>
#include <clang/Frontend/ASTUnit.h>
#include <clang/Frontend/ChainedDiagnosticConsumer.h>
#include <clang/Frontend/CommandLineSourceLoc.h>
#include <clang/Frontend/CompilerInstance.h>
#include <clang/Frontend/CompilerInvocation.h>
#include <clang/Frontend/DependencyOutputOptions.h>
#include <clang/Frontend/DiagnosticRenderer.h>
#include <clang/Frontend/FrontendAction.h>
#include <clang/Frontend/FrontendActions.h>
#include <clang/Frontend/FrontendDiagnostic.h>
#include <clang/Frontend/FrontendOptions.h>
#include <clang/Frontend/FrontendPluginRegistry.h>
#include <clang/Frontend/LayoutOverrideSource.h>
#include <clang/Frontend/LogDiagnosticPrinter.h>
#include <clang/Frontend/MigratorOptions.h>
#include <clang/Frontend/MultiplexConsumer.h>
#include <clang/Frontend/PCHContainerOperations.h>
#include <clang/Frontend/PrecompiledPreamble.h>
#include <clang/Frontend/PreprocessorOutputOptions.h>
#include <clang/Frontend/SARIFDiagnostic.h>
#include <clang/Frontend/SARIFDiagnosticPrinter.h>
#include <clang/Frontend/SerializedDiagnosticPrinter.h>
#include <clang/Frontend/SerializedDiagnosticReader.h>
#include <clang/Frontend/SerializedDiagnostics.h>
#include <clang/Frontend/TextDiagnostic.h>
#include <clang/Frontend/TextDiagnosticBuffer.h>
#include <clang/Frontend/TextDiagnosticPrinter.h>
#include <clang/Frontend/Utils.h>
#include <clang/Frontend/VerifyDiagnosticConsumer.h>
